apiVersion: apps/v1
kind: Deployment
metadata:
  name: keda-operator
  namespace: keda
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: keda-operator
          args:
            - "--disable-webhooks"
          env:
            - name: DISABLE_WEBHOOKS
              value: "true"
          resources:
            requests:
              cpu: "75m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
