apiVersion: apps/v1
kind: Deployment
metadata:
  name: keda-operator
  namespace: keda
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: keda-operator
          args:
            - "--enable-cert-rotation"
          resources:
            requests:
              cpu: "75m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          volumeMounts:
            - name: keda-certs
              mountPath: /certs
              readOnly: false
      volumes:
        - name: keda-certs
          emptyDir: {}
