apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keda-operator
rules:
- apiGroups: ["keda.sh"]
  resources: ["scaledobjects", "triggerauthentications", "clustertriggerauthentications", "scaledjobs"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["pods", "events", "secrets"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["*"]
 - apiGroups: ["admissionregistration.k8s.io"]
   resources: ["validatingwebhookconfigurations"]
   verbs: ["get", "list", "watch", "create", "update", "patch"]
 - apiGroups: ["apiregistration.k8s.io"]
   resources: ["apiservices"]
   verbs: ["get", "list", "watch", "create", "update", "patch"]