apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1 # adjust if you want a highly available setup
  template:
    spec:
      containers:
        - name: redis
          image: redis:7.0.11
          resources:
            limits:
              memory: "256Mi"
              cpu: "250m"
            requests:
              memory: "128Mi"
              cpu: "100m"
