apiVersion: batch/v1
kind: CronJob
metadata:
  name: trigger-worker3
spec:
  schedule: "12 5 * * *" # 5:12 AM daily
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: curl-worker3
              image: curlimages/curl:latest
              command: ["curl"]
              args: ["-X", "GET", "http://ledger-backend-service/worker3"]
          restartPolicy: OnFailure
