apiVersion: batch/v1
kind: CronJob
metadata:
  name: trigger-worker2
spec:
  schedule: "0 0 * * *" # Midnight daily
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: curl-worker2
              image: curlimages/curl:8.8.0
              command: ["curl"]
              args: ["-X", "GET", "http://ledger-backend-service/worker2"]
          restartPolicy: OnFailure
