apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace for all resources
namespace: ledgers

# Base resources
resources:
  - backend-deployment.yaml
  - redis-deployment.yaml
  - worker-deployment.yaml
  - services/backend-service.yaml
  - services/redis-service.yaml
  - cronjobs/trigger-worker1-cronjob.yaml
  - cronjobs/trigger-worker2-cronjob.yaml
  - cronjobs/trigger-worker3-cronjob.yaml
  - scaledobjects/worker-scaledobjects.yaml
  - ingress.yaml
