apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledger-worker
  labels:
    app: ledger-worker
    app.kubernetes.io/name: ledger-worker
    app.kubernetes.io/part-of: my-ledger
spec:
  replicas: 1 # reduced to mitigate resource constraints; override in overlays as needed
  selector:
    matchLabels:
      app: ledger-worker
  template:
    metadata:
      labels:
        app: ledger-worker
        app.kubernetes.io/name: ledger-worker
        app.kubernetes.io/part-of: my-ledger
    spec:
      containers:
        - name: ledger-worker
          image: sm7rth/my-ledger-worker:554d70a77fd835a66430451e87e699b14c8df5ed
          ports:
            - containerPort: 3002
          envFrom:
            - secretRef:
                name: ledger-worker-secret # references decrypted secret
          env:
            - name: NODE_ENV
              value: "production"
            - name: REDIS_URL
              value: "redis://ledger-redis:6379" # reference Redis Service name
          resources:
            requests:
              cpu: "25m"
              memory: "96Mi"
            limits:
              cpu: "150m"
              memory: "192Mi"
          livenessProbe:
            tcpSocket:
              port: 3002
            initialDelaySeconds: 10
            periodSeconds: 20
          readinessProbe:
            tcpSocket:
              port: 3002
            initialDelaySeconds: 5
            periodSeconds: 10
